services:
  postgres:
    image: postgres:16-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
      - POSTGRES_DB=test_db

  otel-collector:
    image: otel/opentelemetry-collector:latest
    ports:
      - 4317:4317